// examples/react/src/App.jsx
import { useEffect, useRef } from 'react';
import initParticleJS from 'particletext.js';
import './App.css';

function App() {
  const canvasRef = useRef(null);
  const particleRef = useRef(null);

  useEffect(() => {
    if (canvasRef.current) {
      particleRef.current = initParticleJS(canvasRef.current, {
        text: 'Particle Text',
        colors: ['#61DAFB', '#282C34', '#20232A'],
        fontSize: 80,
        particleRadius: {
          xxxs: { base: 1, rand: 1 },
          sm: { base: 1.5, rand: 1 },
          md: { base: 2, rand: 1 },
        },
        explosionRadius: {
          xxxs: 40,
          sm: 60,
          md: 80,
          lg: 100,
        },
      });
    }

    return () => {
      if (particleRef.current && particleRef.current.destroy) {
        particleRef.current.destroy();
      }
    };
  }, []);

  return (
    <div className="app">
      <div className="container">
        <h1>ParticleText.js + React</h1>
        <p className="subtitle">Interactive particle text animation built with React</p>
        <div className="canvas-wrapper">
          <canvas
            ref={canvasRef}
            width={1200}
            height={400}
            className="particle-canvas"
          />
        </div>
        <div className="info">
          <p>Move your mouse over the text to interact with the particles!</p>
        </div>
      </div>
    </div>
  );
}

export default App;

// examples/angular/src/app/app.component.ts
import { Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit, OnDestroy {
  @ViewChild('particleCanvas', { static: true }) canvasRef!: ElementRef<HTMLCanvasElement>;

  private particleInstance: any;

  async ngOnInit(): Promise<void> {
    if (this.canvasRef?.nativeElement) {
      // Dynamic import to handle module loading
      const particleModule: any = await import('particletext.js');
      const initParticleJS = particleModule.default || particleModule;

      this.particleInstance = initParticleJS(this.canvasRef.nativeElement, {
        text: 'Particle Text',
        colors: ['#DD0031', '#C3002F', '#1976D2'],
        fontSize: 80,
        particleRadius: {
          xxxs: { base: 1, rand: 1 },
          sm: { base: 1.5, rand: 1 },
          md: { base: 2, rand: 1 },
        },
        explosionRadius: {
          xxxs: 40,
          sm: 60,
          md: 80,
          lg: 100,
        },
      });
    }
  }

  ngOnDestroy(): void {
    if (this.particleInstance && this.particleInstance.destroy) {
      this.particleInstance.destroy();
    }
  }
}

<div class="app">
  <div class="container">
    <h1>ParticleText.js + Angular</h1>
    <p class="subtitle">Interactive particle text animation built with Angular</p>
    <div class="canvas-wrapper">
      <canvas
        #particleCanvas
        width="1200"
        height="400"
        class="particle-canvas"
      ></canvas>
    </div>
    <div class="info">
      <p>Move your mouse over the text to interact with the particles!</p>
    </div>
  </div>
</div>
