// examples/nextjs/src/app/page.tsx
'use client';

import { useEffect, useRef } from 'react';
import styles from './page.module.css';

export default function Home() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const particleRef = useRef<any>(null);

  useEffect(() => {
    const loadParticleText = async () => {
      if (canvasRef.current) {
        const particleModule: any = await import('particletext.js');
        const initParticleJS = particleModule.default || particleModule;

        particleRef.current = initParticleJS(canvasRef.current, {
          text: 'Particle Text',
          colors: ['#000000', '#0070f3', '#666666'],
          fontSize: 80,
          particleRadius: {
            xxxs: { base: 1, rand: 1 },
            sm: { base: 1.5, rand: 1 },
            md: { base: 2, rand: 1 },
          },
          explosionRadius: {
            xxxs: 40,
            sm: 60,
            md: 80,
            lg: 100,
          },
        });
      }
    };

    loadParticleText();

    return () => {
      if (particleRef.current && particleRef.current.destroy) {
        particleRef.current.destroy();
      }
    };
  }, []);

  return (
    <div className={styles.app}>
      <div className={styles.container}>
        <h1>ParticleText.js + Next.js</h1>
        <p className={styles.subtitle}>
          Interactive particle text animation built with Next.js
        </p>
        <div className={styles.canvasWrapper}>
          <canvas
            ref={canvasRef}
            width={1200}
            height={400}
            className={styles.particleCanvas}
          />
        </div>
        <div className={styles.info}>
          <p>Move your mouse over the text to interact with the particles!</p>
        </div>
      </div>
    </div>
  );
}

// examples/angular/src/app/app.component.ts
import { Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit, OnDestroy {
  @ViewChild('particleCanvas', { static: true }) canvasRef!: ElementRef<HTMLCanvasElement>;

  private particleInstance: any;

  async ngOnInit(): Promise<void> {
    if (this.canvasRef?.nativeElement) {
      // Dynamic import to handle module loading
      const particleModule: any = await import('particletext.js');
      const initParticleJS = particleModule.default || particleModule;

      this.particleInstance = initParticleJS(this.canvasRef.nativeElement, {
        text: 'Particle Text',
        colors: ['#DD0031', '#C3002F', '#1976D2'],
        fontSize: 80,
        particleRadius: {
          xxxs: { base: 1, rand: 1 },
          sm: { base: 1.5, rand: 1 },
          md: { base: 2, rand: 1 },
        },
        explosionRadius: {
          xxxs: 40,
          sm: 60,
          md: 80,
          lg: 100,
        },
      });
    }
  }

  ngOnDestroy(): void {
    if (this.particleInstance && this.particleInstance.destroy) {
      this.particleInstance.destroy();
    }
  }
}

<div class="app">
  <div class="container">
    <h1>ParticleText.js + Angular</h1>
    <p class="subtitle">Interactive particle text animation built with Angular</p>
    <div class="canvas-wrapper">
      <canvas
        #particleCanvas
        width="1200"
        height="400"
        class="particle-canvas"
      ></canvas>
    </div>
    <div class="info">
      <p>Move your mouse over the text to interact with the particles!</p>
    </div>
  </div>
</div>
